import { v4 as uuid } from "uuid";

export default function dataInstructores() {
  const data = [
    {
      id: uuid(),
      nombre: "Christian Velasco",
      puesto: "Head de Alura e instructor",
      foto: "https://github.com/christianpva.png",
      equipo: "Programación",
      fav: true,
    },
    {
      id: uuid(),
      nombre: "Christian Velasco",
      puesto: "Head de Alura e instructor",
      foto: "https://github.com/christianpva.png",
      equipo: "Front End",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Christian Velasco",
      puesto: "Head de Alura e instructor",
      foto: "https://github.com/christianpva.png",
      equipo: "Data Science",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Christian Velasco",
      puesto: "Head de Alura e instructor",
      foto: "https://github.com/christianpva.png",
      equipo: "Devops",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Christian Velasco",
      puesto: "Head de Alura e instructor",
      foto: "https://github.com/christianpva.png",
      equipo: "UX y Diseño",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Christian Velasco",
      puesto: "Head de Alura e instructor",
      foto: "https://github.com/christianpva.png",
      equipo: "Móvil",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Christian Velasco",
      puesto: "Head de Alura e instructor",
      foto: "https://github.com/christianpva.png",
      equipo: "Innovación y  Gestión",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Genesys Rondón",
      puesto: "Desarrolladora de software e instructora",
      foto: "https://github.com/genesysR-dev.png",
      equipo: "Programación",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Genesys Rondón",
      puesto: "Desarrolladora de software e instructora",
      foto: "https://github.com/genesysR-dev.png",
      equipo: "Front End",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Genesys Rondón",
      puesto: "Desarrolladora de software e instructora",
      foto: "https://github.com/genesysR-dev.png",
      equipo: "Data Science",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Genesys Rondón",
      puesto: "Desarrolladora de software e instructora",
      foto: "https://github.com/genesysR-dev.png",
      equipo: "Devops",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Genesys Rondón",
      puesto: "Desarrolladora de software e instructora",
      foto: "https://github.com/genesysR-dev.png",
      equipo: "UX y Diseño",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Genesys Rondón",
      puesto: "Desarrolladora de software e instructora",
      foto: "https://github.com/genesysR-dev.png",
      equipo: "Móvil",
      fav: false,
    },
    {
      id: uuid(),
      nombre: "Genesys Rondón",
      puesto: "Desarrolladora de software e instructora",
      foto: "https://github.com/genesysR-dev.png",
      equipo: "Innovación y  Gestión",
      fav: false,
    },
  ];

  return data;
}
